### ISSUE TITLE
I would advise against using this

### ISSUE THREAD

**Issue by alexbudin** [josantonius/php-mime-type#10]
With this library you are getting the mime type based on the file extension and not the actual mime type of the file, based on the file content (the actual binary data), which is s HUGE security problem. If someone uses this with form submitted files, they are introducing a massive security hole in their code as the extension of the file can be easily changed by anyone so that they can easily upload a file.

You must place a warning in your readme so that this is not used for form upload purposes or for public facing projects.

Have a look at how PHP does this with the function **mime_content_type** and look for actual code and you will see that it actually opens the file to read the first bytes.

I realize that you specify that this library determines the mime type from an extension, but you need to warn people about the dangers of that in case someone less experienced uses this for production ready projects where security is very important.

Hope this helps and does not get deleted.

**Comment by josantonius** [comment]
This isn't a issue.

It is answered here: [#11.](https://github.com/josantonius/php-mime-type/discussions/11#discussioncomment-4171634).
